name: neurobench-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - pillow
  - imageio
  - tifffile
  - tqdm
  - psutil
  - pyyaml
  - jsonschema
  - pytest
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cupy
  - pip
  - pip:
      - nvidia-ml-py
