from __future__ import annotations

import unittest


class WorkbenchStructureTests(unittest.TestCase):
    def test_template_contains_accessible_roi_context_and_pipeline_builder(self):
        from tools import build_neuron_workbench_v2 as builder

        html = builder.HTML_TEMPLATE
        self.assertIn("reviewEvidenceGrid", html)
        self.assertIn('aria-labelledby="selectedRoiContextHeading"', html)
        self.assertIn('id="selectedRoiContextHeading"', html)
        self.assertIn('id="architectureBuildPanel"', html)
        self.assertIn('id="experimentsPage"', html)
        self.assertIn('id="experimentLab"', html)
        self.assertIn('href="#experiments"', html)
        self.assertIn('id="pipelineStagePalette"', html)
        self.assertIn('id="pipelineJsonPreview"', html)
        self.assertIn('id="architecturePresetGallery"', html)
        self.assertIn('id="componentLibrary"', html)
        self.assertIn('value="adaptive_cfar"', html)
        self.assertIn('value="artifact_suppression"', html)
        self.assertIn('value="high_recall_discovery"', html)
        self.assertIn("Advanced Manifest Preview", html)
        self.assertIn('value="strongNeuron"', html)
        self.assertIn('value="needsEventReview"', html)
        self.assertIn('value="annotationBatch"', html)
        self.assertIn('value="missingReviewer"', html)
        self.assertIn('value="reviewedByMe"', html)
        self.assertIn('value="reviewedByOther"', html)
        self.assertIn('id="guidedPanel"', html)
        self.assertIn('id="reviewSessionPanel"', html)
        self.assertIn('aria-label="Review session checklist"', html)
        self.assertIn('id="reportPage"', html)
        self.assertIn('href="#report"', html)
        self.assertIn('id="activeRunSelect"', html)
        self.assertIn('id="runGeneratePanel"', html)
        self.assertIn('id="generationBackend"', html)
        self.assertIn('id="previewRunViewBtn"', html)
        self.assertIn('id="unlockGenerationBtn"', html)
        self.assertIn('id="overlayPresetSelect"', html)
        self.assertIn('id="selectedOverlayMode"', html)
        self.assertIn('id="selectedFillOpacity"', html)
        self.assertIn('id="selectedOutlineWidth"', html)
        self.assertIn('id="traceResetZoomBtn"', html)
        self.assertIn('id="traceWindowText"', html)
        self.assertIn('id="eventTimelineCanvas"', html)
        self.assertIn('id="roiFocusMode"', html)
        self.assertIn('id="reviewWorkflowPreset"', html)
        self.assertIn('id="shortcutHelpBtn"', html)
        self.assertIn('id="shortcutOverlay"', html)
        self.assertIn('id="quickJumpInput"', html)
        self.assertIn('id="quickJumpBtn"', html)
        self.assertIn('id="undoAnnotationBtn"', html)
        self.assertIn("Ctrl/Cmd Z", html)
        self.assertIn("Next / previous event queue item", html)
        self.assertIn("Promote suggestion / promote and next", html)
        self.assertIn('id="bookmarkAddBtn"', html)
        self.assertIn('id="bookmarkSelect"', html)
        self.assertIn('id="bookmarkGoBtn"', html)
        self.assertIn('id="uiMode"', html)
        self.assertIn('id="reviewerIdInput"', html)
        self.assertIn('id="nextMissingReviewerBtn"', html)
        self.assertIn('id="stampSelectedReviewerBtn"', html)
        self.assertIn('id="stampMissingReviewerBtn"', html)
        self.assertIn('id="exportProvenanceAuditBtn"', html)
        self.assertIn('class="advancedOnly"', html)
        self.assertIn('id="manualRoiMode"', html)
        self.assertIn('id="manualRoiRadius"', html)
        self.assertIn('id="roiEditMode"', html)
        self.assertIn('id="roiEditBrushRadius"', html)
        self.assertIn('id="roiEditDoneBtn"', html)
        self.assertIn('id="roiEditUndoBtn"', html)
        self.assertIn('id="roiEditRevertBtn"', html)
        self.assertIn('id="materializeManualTracesBtn"', html)
        self.assertIn('id="bulkAcceptBtn"', html)
        self.assertIn('id="bulkRejectBtn"', html)
        self.assertIn('id="bulkUnsureBtn"', html)
        self.assertIn('id="queuePrevBtn"', html)
        self.assertIn('id="queueNextBtn"', html)
        self.assertIn('id="queueStatusText"', html)
        self.assertIn('id="nextActiveRoiBtn"', html)
        self.assertIn('id="acceptNextBtn"', html)
        self.assertIn('id="strongNeuronNextBtn"', html)
        self.assertIn('id="artifactRoiNextBtn"', html)
        self.assertIn('id="missedNeuronModeBtn"', html)
        self.assertIn('id="parameterSnapshotSelect"', html)
        self.assertIn('id="recoverySnapshotSelect"', html)
        self.assertIn('id="recoveryRestoreBtn"', html)
        self.assertIn('id="exportScreenshotBtn"', html)
        self.assertIn('id="roiConfidence"', html)
        self.assertIn('id="roiReasonTags"', html)
        self.assertIn('id="eventConfidence"', html)
        self.assertIn('id="eventQueueSelect"', html)
        self.assertIn('id="eventQueuePrevBtn"', html)
        self.assertIn('id="eventQueueNextBtn"', html)
        self.assertIn('id="eventQueueStatusText"', html)
        self.assertIn('id="eventRejectNextBtn"', html)
        self.assertIn('id="eventUnsureNextBtn"', html)
        self.assertIn('id="eventArtifactNextBtn"', html)
        self.assertIn('id="suggestionConfidence"', html)
        self.assertIn('id="suggestionPromoteNextBtn"', html)
        self.assertIn('id="suggestionQueuePrevBtn"', html)
        self.assertIn('id="suggestionQueueNextBtn"', html)
        self.assertIn('id="suggestionQueueStatusText"', html)
        self.assertIn('id="visualSplitBtn"', html)
        self.assertIn('id="exportSplitMergeBtn"', html)
        self.assertIn('id="exportActiveRoiQueueBtn"', html)
        self.assertIn('id="exportActiveEventQueueBtn"', html)
        self.assertIn('id="exportActiveSuggestionQueueBtn"', html)
        self.assertIn('href="#process"', html)
        self.assertIn("Process Lab", html)
        self.assertIn("Generate View", html)

    def test_asset_js_uses_keyboardable_filmstrip_and_planned_run_builder(self):
        from pathlib import Path

        js = Path("neurobench/workbench/assets/workbench.js").read_text(encoding="utf-8")
        self.assertIn("document.createElement('button')", js)
        self.assertIn("aria-current", js)
        self.assertIn("execution: {status: 'planned'}", js)
        self.assertIn("architecture_runs.json", js)
        self.assertIn("stageIssueBadge", js)
        self.assertIn("plannedManifest", js)
        self.assertIn("sweepFactors", js)
        self.assertIn("triage_queue_counts", js)
        self.assertIn("buildStageCatalog(data.pipelineCatalog)", js)
        self.assertIn("pipelineRealtimeSummary", js)
        self.assertIn("parameterHelp", js)
        self.assertIn("nextAnnotationBatch", js)
        self.assertIn("Recommended Next Annotation Batch", js)
        self.assertIn("tuning_ready", js)
        self.assertIn("guidedTasks", js)
        self.assertIn("renderGuidedPanel", js)
        self.assertIn("sessionChecklistState", js)
        self.assertIn("renderReviewSessionPanel", js)
        self.assertIn("reviewSessionHandoffMarkdown", js)
        self.assertIn("sessionHandoffMarkdownBtn", js)
        self.assertIn("guidedActionButtons", js)
        self.assertIn("applyGuidedAction", js)
        self.assertIn("data-guided-action", js)
        self.assertIn("renderReviewReport", js)
        self.assertIn("renderRobustnessExampleGallery", js)
        self.assertIn("renderAdjudicationPanel", js)
        self.assertIn("clientAgreementReport", js)
        self.assertIn("renderValidationBenchmarkPanel", js)
        self.assertIn("Synthetic latency smoke test", js)
        self.assertIn("robustnessExampleGallery", js)
        self.assertIn("reviewer_counts", js)
        self.assertIn("reviewer_missing", js)
        self.assertIn("labels missing reviewer", js)
        self.assertIn("Backfill missing reviewer IDs", js)
        self.assertIn("Reviewer Contributions", js)
        self.assertIn("Reviewer contributions", js)
        self.assertIn("ARCHITECTURE_PRESETS", js)
        self.assertIn("renderComponentLibrary", js)
        self.assertIn("renderArchitecturePresets", js)
        self.assertIn("renderExperimentLab", js)
        self.assertIn("experimentManifest", js)
        self.assertIn("saveExperimentPlan", js)
        self.assertIn("generateExperimentPreview", js)
        self.assertIn("hash === 'experiments'", js)
        self.assertIn("availabilityBadge", js)
        self.assertIn("expected_qc_outputs", js)
        self.assertIn("qcRunSelect", js)
        self.assertIn("qcFrameSlider", js)
        self.assertIn("renderQcStageTimeline", js)
        self.assertIn("updateQcFrameView", js)
        self.assertIn("hash === 'process'", js)
        self.assertIn("renderParameterExperiments", js)
        self.assertIn("artifactReasonsForRoi", js)
        self.assertIn("rebaseReviewDataAssets", js)
        self.assertIn("activeRunId", js)
        self.assertIn("materializeRunAnnotations", js)
        self.assertIn("loadReviewForRun", js)
        self.assertIn("reviewCompare", js)
        self.assertIn("fetchReviewDataForRun", js)
        self.assertIn("reviewDataCache", js)
        self.assertIn("renderReviewComparisonViewer", js)
        self.assertIn("loadReviewComparison", js)
        self.assertIn("nextReviewComparisonDifference", js)
        self.assertIn("reviewFrameEventCounts", js)
        self.assertIn("Next Difference", js)
        self.assertIn("Synchronized A/B Review", js)
        self.assertIn("Use A In Review/QC", js)
        self.assertIn("generationCommandForRun", js)
        self.assertIn("qcStageGrid", js)
        self.assertIn("intermediateArtifactsForRun", js)
        self.assertIn("apiUrl", js)
        self.assertIn("startGenerationJob", js)
        self.assertIn("generationHeaders", js)
        self.assertIn("ownerTokenKey", js)
        self.assertIn("generate-preview", js)
        self.assertIn("pollGenerationJob", js)
        self.assertIn("backendReadiness", js)
        self.assertIn("traceEventCache", js)
        self.assertIn("TRACE_CACHE_LIMIT", js)
        self.assertIn("cacheSetBounded", js)
        self.assertIn("clearTraceCaches", js)
        self.assertIn("clearTraceEventCache", js)
        self.assertIn("eventCacheKey", js)
        self.assertIn("traceCacheStats", js)
        self.assertIn("if(id === 'eventThreshold') clearTraceEventCache(id);", js)
        self.assertIn("if(id === 'kalmanGain' || id === 'spikeGain') clearTraceCaches(id);", js)
        self.assertIn("splitMergeDecisions", js)
        self.assertIn("migrateSplitMergeDecision", js)
        self.assertIn("createVisualSplitDecision", js)
        self.assertIn("drawSplitMergeGuides", js)
        self.assertIn("exportRows('splitMerge')", js)
        self.assertIn("exportActiveQueue", js)
        self.assertIn("active_event_queue.tsv", js)
        self.assertIn("active_suggestion_queue.tsv", js)
        self.assertIn("reason_tags\\treviewer_id\\tupdatedAt", js)
        self.assertIn("selectedOverlayFillAlpha", js)
        self.assertIn("selectedOverlayMode", js)
        self.assertIn("applyOverlayPreset", js)
        self.assertIn("REVIEW_WORKFLOW_PRESETS", js)
        self.assertIn("applyReviewWorkflowPreset", js)
        self.assertIn("toggleShortcutHelp", js)
        self.assertIn("reviewWorkflowPreset", js)
        self.assertIn("quickJump", js)
        self.assertIn("addReviewBookmark", js)
        self.assertIn("goToReviewBookmark", js)
        self.assertIn("deleteReviewBookmark", js)
        self.assertIn("migrateBookmark", js)
        self.assertIn("annotationUndoStack", js)
        self.assertIn("undoLastAnnotationChange", js)
        self.assertIn("pushAnnotationUndo", js)
        self.assertIn("currentReviewerId", js)
        self.assertIn("stampAnnotation", js)
        self.assertIn("stampSelectedReviewer", js)
        self.assertIn("stampMissingReviewerLabels", js)
        self.assertIn("reviewer_stamp_missing", js)
        self.assertIn("reviewerIdInput", js)
        self.assertIn("roiReviewerId", js)
        self.assertIn("reviewerProvenanceAudit", js)
        self.assertIn("exportReviewerProvenanceAudit", js)
        self.assertIn("nextMissingReviewerLabel", js)
        self.assertIn("Download Provenance Audit", js)
        self.assertIn("eventQueueItems", js)
        self.assertIn("visibleEventsForRoi", js)
        self.assertIn("nextEventQueue", js)
        self.assertIn("advanceEventFromRows", js)
        self.assertIn("markRoiStrongAndNext", js)
        self.assertIn("markRoiArtifactAndNext", js)
        self.assertIn("markEventArtifactAndNext", js)
        self.assertIn("eventQueueStatusText", js)
        self.assertIn("e.key === 'N'", js)
        self.assertIn("e.key === '.'", js)
        self.assertIn("promoteSuggestionAndNext", js)
        self.assertIn("missingReviewer", js)
        self.assertIn("reviewedByMe", js)
        self.assertIn("traceFrameFromX", js)
        self.assertIn("resetTraceZoom", js)
        self.assertIn("traceEventAtPoint", js)
        self.assertIn("traceCanvas.addEventListener('pointerdown'", js)
        self.assertIn("traceCanvas.addEventListener('wheel'", js)
        self.assertIn("drawEventTimeline", js)
        self.assertIn("timelineEventCounts", js)
        self.assertIn("roiFocusMode", js)
        self.assertIn("nextRoiMatching", js)
        self.assertIn("activateMissedNeuronMode", js)
        self.assertIn("saveParameterSnapshot", js)
        self.assertIn("recoveryStoreKey", js)
        self.assertIn("pushRecoverySnapshot", js)
        self.assertIn("restoreRecoverySnapshot", js)
        self.assertIn("exportCurrentViewPng", js)
        self.assertIn("applyUiMode", js)
        self.assertIn("manualRoiState", js)
        self.assertIn("roiEditState", js)
        self.assertIn("createManualRoi", js)
        self.assertIn("ensureEditableRoi", js)
        self.assertIn("applyRoiBrush", js)
        self.assertIn("pushRoiEditHistory", js)
        self.assertIn("undoRoiEdit", js)
        self.assertIn("revertEditedRoiToSource", js)
        self.assertIn("clearMaterializedTraceFields", js)
        self.assertIn("roi_brush_edit", js)
        self.assertIn("materializeManualTraces", js)
        self.assertIn("materialize-traces", js)
        self.assertIn("circlePoints", js)
        self.assertIn("lassoPoints", js)
        self.assertIn("setRoiStateAndNext", js)
        self.assertIn("setSelectedRoisState", js)
        self.assertIn("roi_bulk_accept", js)
        self.assertIn("queueStatusText", js)
        self.assertIn("queueNextBtn", js)
        self.assertIn("roiReasonTags", js)
        self.assertIn("suggestionReasonTags", js)
        self.assertIn("nextSuggestion", js)
        self.assertIn("setSuggestionStateAndNext", js)
        self.assertIn("promoteSuggestionAndNext", js)
        self.assertIn("markSuggestionDuplicateAndNext", js)
        self.assertIn("suggestionQueueStatusText", js)

    def test_legacy_builder_embedded_js_has_trace_cache_hooks(self):
        from pathlib import Path

        js = Path("tools/build_neuron_workbench_v2.py").read_text(encoding="utf-8")
        self.assertIn("traceEventCache", js)
        self.assertIn("TRACE_CACHE_LIMIT", js)
        self.assertIn("clearTraceCaches", js)
        self.assertIn("clearTraceEventCache", js)
        self.assertIn("eventCacheKey", js)
        self.assertIn("traceCacheStats", js)

    def test_intermediate_export_tool_exposes_manifest_fields(self):
        from pathlib import Path

        script = Path("tools/export_intermediate_frames.py").read_text(encoding="utf-8")
        self.assertIn('"frame_pattern"', script)
        self.assertIn('"media_type": "frame_sequence"', script)
        self.assertIn('"intermediates"', script)


if __name__ == "__main__":
    unittest.main()
